feat(consumer): Many namespace
majusko/pulsar-java-spring-boot-starter pull request #202
Opened 2022-01-13 14:22 UTC by DreamingOfDreams

In annotation additional namespace, supports multiple different namespaces to add multiple different namespaces in the project.

2022-01-13 17:33 UTC, majusko commented
Thank you. I will do a code review.

2022-01-13 17:46 UTC, majusko commented
@DreamingOfDreams Thank you very much for your contribution to the project.  It can be merged right after applying some minor changes from the code review.

2022-01-14 01:38 UTC, DreamingOfDreams commented
You're welcome. I hope the project is getting better and better. Please forgive my plastic English. I hope more and more people will use it and contribute to it.

2022-01-16 10:35 UTC, majusko commented
@DreamingOfDreams Not in hurry but when are you planning to implement the required changes in a code review? I plan to do a patch release soon and I would like to include your changes there as well.

2022-01-19 02:36 UTC, DreamingOfDreams commented
okay, no problem

2022-01-19 13:08 UTC, majusko requested changes

2022-01-19 13:09 UTC, majusko commented
@DreamingOfDreams Sorry, I did not hit the "Submit change request" button. That is why I was waiting for a change and you did not see the request 🤦‍♂️

2022-01-24 15:24 UTC, DreamingOfDreams commented on src/main/java/io/github/majusko/pulsar/consumer/ConsumerAggregator.java
> +                    .filter(holder -> holder.getValue().getAnnotation().autoStart())
okay, no problem

2022-01-24 15:28 UTC, DreamingOfDreams commented
@majusko OK, no problem. There are too many things in the company recently. It will be updated later for the Spring Festival in a few days. I'm sorry.

2022-03-11 09:10 UTC, shodo commented
Hi, I need this feature too, when it will be merged? Can I help somehow?

2022-03-11 09:59 UTC, majusko commented
Hey @shodo, There is a code review with changes that are required before merging. @DreamingOfDreams When do you think you can have a look into this?

2022-03-11 10:36 UTC, shodo commented
If @DreamingOfDreams is busy I can try to take his branch and make the requested changes. I'm not familiar with GitHub workflow (I use bitbucket at work) but I can try

2022-03-11 12:09 UTC, majusko commented
@shodo I'm afraid that @DreamingOfDreams forget to commit `UrlBuildService` file that is the most important change because that is the file where the namespace is hardcoded to the default one now. But I think you can try to make it happen based on his code. It shouldn't be that complicated change and you have some sort of base here.

2022-03-11 14:57 UTC, shodo commented
@majusko Ok I'll give a try!

2022-03-15 23:43 UTC, merged

2022-04-04 18:41 UTC, shodo commented
Hi @majusko I've finally opened a PR. Sorry for that delay but I had a lot of work these days. 
Any chance to merge it?

https://github.com/majusko/pulsar-java-spring-boot-starter/pull/227

2022-04-06 08:57 UTC, majusko commented
Merged, fixed a few issues and released in `1.1.1`

2022-04-06 10:54 UTC, shodo commented
@majusko Thanks a lot!